# Generated by Django 5.1.4 on 2024-12-16 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralQuery',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chatbot')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralResponse',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('g_query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.generalquery')),
            ],
        ),
        migrations.CreateModel(
            name='ReportQuery',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('criteria', models.TextField()),
                ('type_of_data', models.TextField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chatbot')),
            ],
        ),
        migrations.CreateModel(
            name='ReportResponse',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('file_link', models.URLField()),
                ('r_query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.reportquery')),
            ],
        ),
    ]
