# Generated by Django 5.1.4 on 2024-12-18 04:52

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_chatbot_id_alter_chatbot_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='id',
            field=models.UUIDField(default=uuid.UUID('409ceeb7-b676-4cca-9e43-dcbbc0b7c493'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='time_created',
            field=models.TimeField(default=datetime.datetime(2024, 12, 18, 4, 52, 31, 713726, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='generalquery',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a8a2e4a4-61f1-4036-a6ea-55b8843e2539'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='generalquery',
            name='time_created',
            field=models.TimeField(default=datetime.datetime(2024, 12, 18, 4, 52, 31, 713967, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='generalresponse',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9ce123a4-f052-4139-a9a0-130620cb9bda'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='generalresponse',
            name='time_created',
            field=models.TimeField(default=datetime.datetime(2024, 12, 18, 4, 52, 31, 714391, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reportquery',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7f1d9b6d-16a3-40c6-88fc-1675961a5908'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reportquery',
            name='time_created',
            field=models.TimeField(default=datetime.datetime(2024, 12, 18, 4, 52, 31, 714182, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reportresponse',
            name='id',
            field=models.UUIDField(default=uuid.UUID('21432b72-73e3-4457-b04a-7673c51b39b8'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reportresponse',
            name='time_created',
            field=models.TimeField(default=datetime.datetime(2024, 12, 18, 4, 52, 31, 714608, tzinfo=datetime.timezone.utc)),
        ),
    ]
