# Generated by Django 5.1.4 on 2024-12-18 04:52

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_chatbot_id_alter_chatbot_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='time_created',
            field=models.TimeField(default=datetime.datetime(2024, 12, 18, 4, 52, 41, 396354, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='generalquery',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='generalquery',
            name='time_created',
            field=models.TimeField(default=datetime.datetime(2024, 12, 18, 4, 52, 41, 396703, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='generalresponse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='generalresponse',
            name='time_created',
            field=models.TimeField(default=datetime.datetime(2024, 12, 18, 4, 52, 41, 397153, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reportquery',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reportquery',
            name='time_created',
            field=models.TimeField(default=datetime.datetime(2024, 12, 18, 4, 52, 41, 396938, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reportresponse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reportresponse',
            name='time_created',
            field=models.TimeField(default=datetime.datetime(2024, 12, 18, 4, 52, 41, 397369, tzinfo=datetime.timezone.utc)),
        ),
    ]
