# Generated by Django 5.1.4 on 2024-12-18 04:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_chatbot_id_alter_chatbot_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='time_created',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='generalquery',
            name='time_created',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='generalresponse',
            name='time_created',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reportquery',
            name='time_created',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reportresponse',
            name='time_created',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
